### ISSUE TITLE
[Bug]: 无法在config.yaml中添加配置

### ISSUE THREAD

**Issue by Raycoi** [ayakasuki/zhenxun_fansMedalHelper#1]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经在 [Issue Tracker](https://github.com/XiaoMiku01/fansMedalHelper/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。

### 粉丝牌助手 版本

1

### 运行环境

Ubuntu

### 运行架构

AMD64

### 部署方式

本地

### 粉丝牌数量

1

### 补充说明（可选）

在服务器重启真寻之后会报错 “读取配置文件失败,请检查配置文件格式是否正确: ASYNC参数错误”  初步排查是config.yaml没有插件的配置信息，但重启真寻配置信息应该自动加进去呀

**Comment by Raycoi** [comment]
ok检查了一下，大概是因为第一次运行时需要读取配置信息，否则就报错退出，但第一次运行配置里面什么都没有，最好加个判断什么的，或者跟我一样懒得改就直接删掉exit(1)就好了，代码报错段如下
(https://user-images.githubusercontent.com/112241195/232218419-19bb0891-ee36-47a3-8d52-4261bd36aac7.png)
修改为
(https://user-images.githubusercontent.com/112241195/232220511-f8d96808-a843-42d8-abdb-71c1176b97b3.png)

**Comment by ayakasuki** [comment]
OK

> ok检查了一下，大概是因为第一次运行时需要读取配置信息，否则就报错退出，但第一次运行配置里面什么都没有，最好加个判断什么的，或者跟我一样懒得改就直接删掉exit(1)就好了，代码报错段如下 (https://user-images.githubusercontent.com/112241195/232218419-19bb0891-ee36-47a3-8d52-4261bd36aac7.png) 修改为 (https://user-images.githubusercontent.com/112241195/232220511-f8d96808-a843-42d8-abdb-71c1176b97b3.png)
